### PR TITLE
upadete the Get in Touch form

### PR DESCRIPTION
**Pull request by Yash-Var**
@RyanWalker277 i have made the necessary changes pls review it ...

### CODE REVIEW

**Review by RyanWalker277 — CHANGES_REQUESTED** [review]
Looks good , but you have only connected the "Get in touch" form at the contact us page , connect the "Get in touch" at the index page to the backend as well.Everything else is fine , great job!

**Comment by Yash-Var** [comment]
okk sir

**Comment by Yash-Var** [comment]
added and i have added jazzmin also pls review

**Comment by Yash-Var** [comment]
@RyanWalker277 pls review and give suggestions

**Comment by RyanWalker277** [comment]
> @RyanWalker277 pls review and give suggestions

Currently I'm a bit busy , I'll review it tomorrow , in the meantime, you can work on other issues

**Review by RyanWalker277 — APPROVED** [review]

**Pull request merged**
