### PR TITLE
Completed the blogs section of the website

### LINKED ISSUE #9: Complete the Blogs Section
# Complete the Blogs Section

## Description
-Make a frontend interface for writing blogs as a seperate page
-Connect the interface to the backend blogs model
-Make the url path for the blog interface and link it to the frontend

## Expected outcomes

A working blogs section on the website

## Skills

Python, Django

## Possible mentors

[Anvansh](https://github.com/RyanWalker277)

## Expected project size

5 hours.

## Difficulty

Easy

### LINKED ISSUE #16: Complete the Blogs Section with full functionality
### Complete the Blogs Section

<h1> Description</h1>

- Make a frontend interface for writing blogs as a seperate page
- Make a frontend interface for posting comments and linking it to the particular comment.
- Connect the interface to the backend blogs and comments model
- Make the url path for the blog interface and link it to the frontend

<h1>Features</h1>

- Only authenticated users can create a new blog
- Anyone can view and read all the blogs.
- Authenticated users can comment on a particular blog (they will only see text-area for writing comment)
- Any unauthenticated person can also leave a comment by adding their **name and email.**
- Implement **pagination** on the blogs section to prevent overcrowding of data.
- Provide a new page to **view all comments** of a particular post.(only if the comments exceed a threshold value)

<h1>Expected outcomes</h1>

A fully functional blogs section on the website with proper **comments** and **pagination** functionality.

<h1>Skills</h1>
Python, Django

<h1>Possible mentors</h1>

[Anvansh](https://github.com/RyanWalker277)

<h1>Expected project size</h1>

10 - 15 hours

### PR DESCRIPTION
**Pull request by prabs222**
# Related Issues or bug
  - Complete the Blogs Section with full functionality

Fixes: #16 ,  fixes #9 

# Proposed Changes

- Make a frontend interface for writing blogs as a seperate page
- Make a frontend interface for posting comments and linking it to the particular comment.
- Connect the interface to the backend blogs and comments model
- Make the url path for the blog interface and link it to the frontend
 
# Additional Info 
<h4>Features added:</h4>

- Only authenticated users can create a new blog
- Anyone can view and read all the blogs.
- Authenticated users can comment on a particular blog (they will only see text-area for writing comment)
- Any unauthenticated person can also leave a comment by adding their **name and email.**
- Implemented **pagination** on the blogs section to prevent overcrowding of data.
- Provided a new page to **view all comments** of a particular post.(only if the comments exceed a threshold value)

# Screenshots

Screenshot from 2023-02-03 22-02-35
<br>
Screenshot from 2023-02-03 22-05-13
<br>
Screenshot from 2023-02-03 22-04-40
<br>
Screenshot from 2023-02-03 22-06-36

### CODE REVIEW

**Comment by prabs222** [comment]
@RyanWalker277 hello sir, I have finished working with the blogs section. Please review my PR and give suggestions.

**Comment by RyanWalker277** [comment]
Hey @prabs222 , I have reviewed your PR and left some reviews. Please do these changes and resolve the merge conflict so that I can merge your pull request.

**Comment by prabs222** [comment]
@RyanWalker277 sir I have resolved the merge conflict, but I could not find the reviews regarding the changes so please tell me how can I view them?

**Comment by RyanWalker277** [comment]
These are called code reviews. When you submit a PR to an open source project , the mantainers review the changes you made to the codebase and leave their feedbacks in this way. It is a good practice to keep your code changes as minimum as possible and properly document your changes for anyone in future to read.

**Comment by prabs222** [comment]
@RyanWalker277 Thank you sir for explaining the matter. Sir I have removed unnecessary comments and the requirements.txt was already up to date. Please tell if any thing else needs to be changed. (Sorry for this silly question, but I am still unable to see the code review, I maybe wrong but guess it's not submitted as it has a pending label)

**Comment by RyanWalker277** [comment]
Oh! My bad , I forgot to submit the review that's why you weren't able to see it. I reviewed your changes , LGTM! Ready to be merged.Good work @prabs222 .I will close the previous issue because they both are same

**Comment by prabs222** [comment]
Thankyou sir.

**Pull request merged**
